swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /info:
    get:
      operationId: VersionInfo
      consumes:
      - '*/*'
      produces:
      - '*/*'
  /users:
    get:
      operationId: FetchAllUsers
      consumes:
      - application/json
      produces:
      - application/json
    post:
      operationId: CreateUser
      consumes:
      - application/json
      produces:
      - application/json
