swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /createUser:
    post:
      operationId: CreateUser
      consumes:
      - application/json
      produces:
      - application/json
  /deleteAllUsers/{key}:
    delete:
      operationId: DeleteAllUsers
      consumes:
      - application/json
      produces:
      - application/json
  /deleteUser/{id}:
    delete:
      operationId: DeleteUser
      consumes:
      - application/json
      produces:
      - application/json
  /getAllUsers:
    get:
      operationId: FetchAllUsers
      consumes:
      - application/json
      produces:
      - application/json
  /getUser/{id}:
    get:
      operationId: FetchUser
      consumes:
      - application/json
      produces:
      - application/json
  /info:
    get:
      operationId: Info
      consumes:
      - '*/*'
      produces:
      - '*/*'
  /updateUser/{id}:
    put:
      operationId: UpdateUser
      consumes:
      - application/json
      produces:
      - application/json
